### PR TITLE
Update builder to check mixins for toJson

### LINKED ISSUE #216: Builder throws "Not compatible with a supported function shape" for freezed objects
I tried making a minimal reproduction of the issue: 

```sh
dartfn version → 0.4.0 
mkdir functions_framework_builder_repro && cd functions_framework_builder_repro  
dartfn generate json
pub get 
```

Then I converted `GreetingResponse` to freezed 
- see the second (and last) commit at [nickmeinhold/functions_framework_builder_repro](https://github.com/nickmeinhold/functions_framework_builder_repro)

Running: `pub run build_runner build` gives: 

```sh
Not compatible with a supported function shape:
  HandlerWithLogger [FutureOr<Response> Function(Request, RequestLogger)] from package:functions_framework/functions_framework.dart
  Handler [FutureOr<Response> Function(Request)] from package:shelf/shelf.dart
  CloudEventWithContextHandler [FutureOr<void> Function(CloudEvent, RequestContext)] from package:functions_framework/functions_framework.dart
  CloudEventHandler [FutureOr<void> Function(CloudEvent)] from package:functions_framework/functions_framework.dart
  JsonHandler [FutureOr<ResponseType> Function(RequestType request, RequestContext context)] from package:functions_framework/functions_framework.dart
  JsonHandler [FutureOr<ResponseType> Function(RequestType request)] from package:functions_framework/functions_framework.dart


package:functions_framework_builder_repro/functions.dart:51:18
   ╷
51 │ GreetingResponse function(GreetingRequest request) {
```

The freezed object has the same getters, as well as a fromJson and toJson. I've started looking into the builder code to determine what `FunctionTypeValidator` is looking for but I'm having trouble following what's happening.  I'll keep trying though. 

Thanks!

### PR DESCRIPTION
**Pull request by nickmeinhold**
- updated _validJsonReturnTypeCore to also check a type's mixins for valid toJson methods

fixes #216

### CODE REVIEW

**Review by subfuzion — CHANGES_REQUESTED** [review]
Hey @nickmeinhold, this looks good -- but can you add a test as well? Let's also get @kevmoo's approval.

**Comment by kevmoo** [comment]
I'd love to have a *test* for this!

Could we get a test in here, @nickmeinhold ?

**Comment by nickmeinhold** [comment]
Will do, thanks!

**Comment by kevmoo** [comment]
Friendly ping, @nickmeinhold – or I may take a look

**Comment by nickmeinhold** [comment]
Thanks for the ping @kevmoo!  Sorry for the delay, the task was more than I expected due to being new to testing custom builders with build_test.  I got distracted but came back and spent some time on this yesterday and will work on it again today.  Please don't let me get in the way if you want it finished or closed though.  Thanks!

**Comment by nickmeinhold** [comment]
I've added a test, sorry again for the delay... starting to get my head around using build_test at least!

**Comment by kevmoo** [comment]
@nickmeinhold try this:

```diff
diff --git a/functions_framework_builder/lib/src/valid_json_utils.dart b/functions_framework_builder/lib/src/valid_json_utils.dart
index bf86a87..2f4f886 100644
--- a/functions_framework_builder/lib/src/valid_json_utils.dart
+++ b/functions_framework_builder/lib/src/valid_json_utils.dart
@@ -99,15 +99,12 @@ JsonReturnKind _validJsonReturnTypeCore(DartType type) {
 
   // Look for a `toJson` function that returns a JSON-able type
   if (type is InterfaceType) {
-    final toJsonMethod = [
-      type.getMethod('toJson'),
-      ...type.mixins.map((mixin) => mixin.getMethod('toJson'))
-    ].firstWhere(
-        (element) =>
-            element != null &&
-            element.parameters.every((element) => element.isOptional),
-        orElse: () => null);
-    if (toJsonMethod != null) type = toJsonMethod.returnType;
+    final toJsonMethod =
+        type.element.lookUpMethod('toJson', type.element.library);
+    if (toJsonMethod != null &&
+        toJsonMethod.parameters.every((element) => element.isOptional)) {
+      type = toJsonMethod.returnType;
+    }
   }
 
   return _validJsonType(type, true)
```

`lookUpMethod` is where we should go here!

**Comment by nickmeinhold** [comment]
Thanks @kevmoo!  Updated.  That's so much nicer.  Great to know about `lookupMethod` too!

**Review by kevmoo — APPROVED** [review]

**Pull request merged**
