### PR TITLE
functions_framework v0.3.2-dev

### PR DESCRIPTION
**Pull request by subfuzion**

### CODE REVIEW

**Comment by kevmoo** [comment]
why is this needed?

Usually we'd do this kind of bump w/ another change to the library

**Comment by subfuzion** [comment]
> why is this needed?
> 
> Usually we'd do this kind of bump w/ another change to the library

So we expect the very next person who wants to add a commit to the functions framework package and submits a PR will *also have to remember* to bump the pubspec then? Unless *everybody* in the Dart world already knows this, we should document this step in the contributing doc. I wouldn't have known this myself.

**Comment by kevmoo** [comment]
what's the story here @subfuzion ?

**Comment by subfuzion** [comment]
Yeah, this is pretty stale, but never got a response to my question.

**Comment by subfuzion** [comment]
I'll go ahead and close it, but let's chat about [my comment](https://github.com/GoogleCloudPlatform/functions-framework-dart/pull/159#issuecomment-751932477) and see if we can make this clearer for others in the docs.

**Pull request closed without merging**
