### PR TITLE
Add Support for Middleware

### PR DESCRIPTION
**Pull request by mtwichel**
## Motivation
As discussed in #222 and #240, It would be nice to support middleware in your Dart functions for tasks like CORS support or authentication. This approach takes inspriation   from [the approach documented with Firebase Cloud Functions](https://firebase.google.com/docs/functions/http-events#use_middleware_modules_with) as well as the existing method of using annotations in the Dart Functions Framework. The approach taken here should also make it very easy to use existing middleware written for `shelf` as it uses the same signatures for middleware methods.

**This change is not breaking!**

## New Usage
You can declare a middleware function like so:

```dart
@CloudFunctionMiddleware()
Handler middleware(Handler handler) {
	// Function goes here
}
```
This will then be injected into the shelf pipeline and run before your actual function code is called.

This function essentially wraps the existing handler function in your middleware function. The handler parameter is that existing handler function.

As a silly example, here’s a function that returns “POST Not Allowed” to any request that uses the POST method, otherwise it returns the underlying function:

```dart
@CloudFunctionMiddleware()
Handler middleware(Handler innerHandler) => (req) {
      if (req.method == 'POST') {
        return Response.ok('POST Not Allowed');
      } else {
        return innerHandler(req);
      }
    };
```

## Technical Details
The PR changes the `serve` method to accept a list of `Middleware`s, which are your middleware functions taged with `@CloudFunctionMiddleware`. These are then passed into the `run` method which adds them to the shelf `Pipeline`. 

During the build step, your functions are identified and added to the `serve` method in the generated `bin/server.dart`. For this, the PR creates new target called a `MiddlewareTarget` which represents the middleware. Since only one method signature is supported, it has one concrete constructor.

Hope you enjoy :)

### CODE REVIEW

**Review by subfuzion — CHANGES_REQUESTED** [review]
@mtwichel Thanks for contributing this. Middleware support will be nice to add. I'd love to see this get landed, so can you please do the following?

* Add tests for this. The appropriate locations for those would be under `functions_framework_builder/test/test_examples/` and `test/hello/test`.
* Address the CI check issues (see details for the failed checks). One thing you can do on your end before pushing your updates is to run `mono_repo presubmit` and `markdownlint-cli2-fix "**/*.md"` from the repo root.

Don't let this block you; feel free to reach out to me directly if you need a hand with anything (tonypujals at google dot com).

Let's also get feedback from @kevmoo.

Thanks!

**Comment by mtwichel** [comment]
Thanks @subfuzion for the feedback! I'll take a look at these issues tonight. Especially thanks for the tip on the tests - I wasn't exactly sure where to slot them in.

**Comment by kevmoo** [comment]
I'm not convinced this is worth the added complexity. It's easy to create a stack of middleware and add it to a function. Having many functions in a project is supported, but I don't think it'd be super common.

**Comment by tobytraylor** [comment]
@kevmoo How do you add a pipeline of middleware to one of the cloud functions.  I can't quite figure it out.

**Comment by jimmyff** [comment]
> @kevmoo How do you add a pipeline of middleware to one of the cloud functions. I can't quite figure it out.

Example here: https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/222#issuecomment-1293372664

**Pull request closed without merging**
