### PR TITLE
Don't register SIGTERM handler on Windows

### LINKED ISSUE #151: Example not working on Windows 😁
This is what I did, also tried running `build_runner` command but no luck.

I use Flutter so does that make some problem for the environment?

```bash
PS C:\Users\yazee\Desktop\hello> dart run .\bin\server.dart
Unhandled exception:
SignalException: Failed to listen for SIGTERM, osError: OS Error: The request is not supported.
, errno = 50
```

Dart Version
```bash
PS C:\Users\yazee> dart --version
Dart SDK version: 2.12.0-141.0.dev (dev) (Thu Dec 10 06:04:48 2020 -0800) on "windows_x64"
```

### PR DESCRIPTION
**Pull request by subfuzion**
(Maybe) Fixes #151 

Registering a SIGTERM handler on Windows raises an exception.

@kevmoo PTAL. Things to consider: this explicitly checks for Windows, but it might be better to just try to catch the exception and then log that the SIGTERM handler couldn't be registered for the host OS.

Before merging this, we should get someone with Windows expertise to weigh in. I left [this comment](https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/151#issuecomment-751812565) in the issue, copied here for convenience:

> While the exception would seem to indicate that SIGTERM isn't supported, I found this [old Microsoft doc](https://docs.microsoft.com/en-us/previous-versions/ms811896(v=msdn.10)?redirectedfrom=MSDN#ucmgch09_topic3) that seems to indicate that SIGTERM *is* supported. 🤷🏻‍♂️

This might or might not be the appropriate fix. There might be an issue with Dart? According to [this Microsoft doc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/signal?view=msvc-160), Windows includes `SIGTERM` for ANSI compatibility:

> The SIGILL and SIGTERM signals are not generated under Windows. They are included for ANSI compatibility.

### CODE REVIEW

**Review by YazeedAlKhalaf — APPROVED** [review]
LGTM 🚀
Tried the changes on my Windows machine and it works!

**Comment by subfuzion** [comment]
@YazeedAlKhalaf Thanks for confirming. I'd still like to get at least one more review from either @kevmoo or @grant just to make sure they also think this is the "right" fix.

**Review by kevmoo — APPROVED** [review]
We should do a follow-up to at least run a sanity check of all tests on windows

**Review by grant — APPROVED** [review]

**Comment by subfuzion** [comment]
> We should do a follow-up to at least run a sanity check of all tests on windows

We should be able to do this with a GitHub CI build ... a dedicated job that only runs a set of dart tests without the bash dependencies we've got (like `tool/ci.sh`).

**Pull request merged**
