### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by kevmoo**
- Remove TODO that's already completed
- Improve error messages and exit codes for failures

### CODE REVIEW

**Review by subfuzion — COMMENTED** [review]
Left a comment for consideration, but feel free to merge when you're ready. Thanks!

**Review by subfuzion — APPROVED** [review]
Left a comment for consideration, but feel free to merge when you're ready. Thanks!

**Review by subfuzion — CHANGES_REQUESTED** [review]
Sorry, approved prematurely. "Correctly return 404 for robots.txt and favicon.ico " really ought to be its own PR ("Closes #2"). Thanks!

**Comment by kevmoo** [comment]
> Sorry, approved prematurely. "Correctly return 404 for robots.txt and favicon.ico " really ought to be its own PR ("Closes #2"). Thanks!

I will land these all separately – no worries!

**Pull request merged**
