### PR TITLE
Bump dartfn to 0.3.2 for windows sigterm fix

### PR DESCRIPTION
**Pull request by subfuzion**

### CODE REVIEW

**Review by kevmoo — CHANGES_REQUESTED** [review]
We should be releasing `functions_framework` right? That's where the fix is...

**Comment by subfuzion** [comment]
> We should be releasing `functions_framework` right? That's where the fix is...

Absolutely right! Need both. Good catch, thanks!

**Comment by subfuzion** [comment]
This one (with a dependency update) should come after the framework bump.

**Comment by kevmoo** [comment]
Do we need both? Is the version fixed?

**Comment by subfuzion** [comment]
> Do we need both? Is the version fixed?

Nah, you're right -- only the templates, but they'll be satisfied with the latest framework, once it's published.

**Pull request closed without merging**
