### PR TITLE
docs: use Docker as the execution environment

### PR DESCRIPTION
**Pull request by brianquinlan**
After this change lands, I'll file a bug to switch to the non-beta version of gcloud when the execution environment feature lands.

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @subfuzion 

Maybe we should just list this as an option? Not sure it's best to have most users go this route.

**Comment by brianquinlan** [comment]
> CC @subfuzion
> 
> Maybe we should just list this as an option? Not sure it's best to have most users go this route.

I think that the problem is that, if the user wants to connect to a database (likely) and uses the recommended approach (likely) then the gen1 execution environment won't work.

I could write some docs explaining why we suggest the gen2 execution environment.

**Comment by kevmoo** [comment]
My guess: connecting to native databases is not uncommon, but it's not a majority of use cases.

For the majority of cases, when you just want to wrap some other REST APIs, etc – we want to avoid recommending beta solutions.

Case in point: the issue that was filed was the first time we've heard of this issue!

**Comment by brianquinlan** [comment]
So should I suggest that if you are consuming a database? And then, when `gen2` is GA then we can recommend it in all situations.

**Pull request closed without merging**
