### PR TITLE
Using a custom shelf server

### PR DESCRIPTION
**Pull request by skay1994**
Add customization capability of shelf http server by a custom function created by user.

## How to

1. Make a file **lib/shelf_custom.dart**
2. Make a function named **shelfServer**, this function receive three parameters
   - **FunctionConfig config**: Environment configuration
   - **Handler handler**: the functions framework handler.
     - Run selected function by *FUNCTION_TARGET* argument 
       or default function in **lib/functions.dart**
   - **FutureOr<bool> shutdownSignal**: Is a signal for shutdownSignal server 
     used by default shelf server.
3. In a **shelfServer** function add your self code, example bellow
4. Run build runner

```dart
import 'dart:async';
import 'dart:io';
import 'package:functions_framework/functions_framework.dart';
import 'package:shelf/shelf.dart';
import 'package:shelf/shelf_io.dart';

void shelfServer(FunctionConfig config, Handler handler,
    FutureOr<bool> shutdownSignal) async {
  final pipeline = const Pipeline()
      .addMiddleware(logRequests())
      .addHandler(handler);

  final server = await serve(
    pipeline,
    InternetAddress.anyIPv4,
    config.port,
  );

  print('Listening on ${server.address.host}:${server.port}');

  final force = await shutdownSignal;
  await server.close(force: force);
}
```

### CODE REVIEW

**Comment by kevmoo** [comment]
@skay1994 – would you file an issue describing what you want to do here?

Thanks!

**Comment by skay1994** [comment]
@kevmoo hey good nigth, i'm tried use same packages for shelf, like a [shelf_cookie](https://pub.dev/packages/shelf_cookie), i realized that the use from another packages becomes impossible because a shelf instance it's locked in functions_framework package

**Comment by kevmoo** [comment]
> @kevmoo hey good nigth, i'm tried use same packages for shelf, like a [shelf_cookie](https://pub.dev/packages/shelf_cookie), i realized that the use from another packages becomes impossible because a shelf instance it's locked in functions_framework package

That doesn't matter, @skay1994 . The framework just spins up the server. You can import any package you want and use it in your handler.

**Comment by skay1994** [comment]
> That doesn't matter, @skay1994 . The framework just spins up the server. You can import any package you want and use it in your handler.

And for packages or a custom handle to applie in Pipeline, like a custom addMiddleware handle?

**Comment by kevmoo** [comment]
> > That doesn't matter, @skay1994 . The framework just spins up the server. You can import any package you want and use it in your handler.
> 
> And for packages or a custom handle to applie in Pipeline, like a custom addMiddleware handle?

Yup. You can invoke whatever you want in your `function` definition. As long as it returns a `Response` (or `Future<Response>`) etc

**Comment by skay1994** [comment]
I understand, I'm going to do some tests, thanks!

**Comment by kevmoo** [comment]
I'm going to close this out for now, @skay1994  – let us know how you want to follow-up.

**Pull request closed without merging**
