### PR TITLE
Fix issue with functions being exported in target lib/functions.dart

### PR DESCRIPTION
**Pull request by kevmoo**
Update test/hello to fully exercise this pattern

### CODE REVIEW

**Review by subfuzion — APPROVED** [review]
This is really coming along nicely!

**Review by subfuzion — CHANGES_REQUESTED** [review]
Oops, too quick on the draw to approve, but will just as soon as passing CI.

**Comment by kevmoo** [comment]
@subfuzion – hopefully fixed w/ this

**Review by subfuzion — APPROVED** [review]
👍

**Pull request merged**
