### PR TITLE
Require functions be defined in lib/function.dart

### PR DESCRIPTION
**Pull request by kevmoo**
Also change generated entry point to `bin/server.dart` over `bin/main.dart` – more standard.
Makes a lot of things easier on the generator
Allows us to have better validation of function "shapes"

### CODE REVIEW

**Review by subfuzion — APPROVED** [review]

**Comment by kevmoo** [comment]
Gah! please squash merge – there's lots of ugly in that PR!

**Comment by kevmoo** [comment]
or just approve and let me land it

**Comment by subfuzion** [comment]
It **was** squashed!

**Comment by kevmoo** [comment]
I did it after the fact

**Pull request merged**
