### PR TITLE
Continue ignoring pubspec.lock for dartfn and test/hello

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Review by subfuzion — COMMENTED** [review]
I do not agree with these changes.

**Comment by kevmoo** [comment]
@subfuzion – let's chat about this. I think this is the right call. Happy to explain.

**Comment by subfuzion** [comment]
Hey @kevmoo, I'm on board with this -- since we're responsible for the cadence of publishing releases for this, and not releasing production "deployments" per se, the idea of pinning things down -- I see where you're coming from now. Apologies for letting this linger for so long. Feel free to get current and self merge.

**Review by subfuzion — APPROVED** [review]
Please feel free to merge after resolving conflicts, thanks!

**Pull request merged**
