### PR TITLE
Cloudevent example use official image

### LINKED ISSUE #229: Update examples/raw_cloudevent to use official image
Will need to take a look at builder framework internals for `'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'`

### PR DESCRIPTION
**Pull request by subfuzion**
This example updates `examples/raw_cloudevent`. It also addresses an issue I noted because we weren't committing `pubspec.lock` files with the sample apps. It removes the top level `.gitignore` and `.dockerignore` files and places them individually tailored for the library packages and sample applications.

Closes #229

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
=)

**Review by grant — APPROVED** [review]

**Review by kevmoo — COMMENTED** [review]
I'm...ambivalent about including the lock files here.

That means we'll have to update these ~often or users won't be getting the latest dependencies.

**Comment by subfuzion** [comment]
I see your point of view. We already had a separate discussion with @mit-mit and I also agreed with following recommended best practices for apps and committing the lock file. When we don't, we run into issues like I did with #229 where a lock file on the users system is out-of-date (and isn't overwritten when pulling the latest). This PR is merged, so let's can continue the discussion in a new issue.

**Comment by mit-mit** [comment]
Why are you ambivalent @kevmoo? These are apps, right?

**Comment by kevmoo** [comment]
> Why are you ambivalent @kevmoo? These are apps, right?

Yes...but they are samples. "pinning" deps for something actively maintained in a team totally makes sense.

For samples...it feels weird.

**Comment by mit-mit** [comment]
Say more. How does it feel weird? Is there some practical issue?

**Comment by kevmoo** [comment]
> Say more. How does it feel weird? Is there some practical issue?

Sorry for being vague.

We want our users to get the latest dependencies, generally. For a deployed app, saving the .lock file makes sense.

This seems like noise. PRs that are just "update deps" are noisy. maybe it's just something I need to get used to. It's a feeling at the moment, but I don't have anything specific to pin it on. Sorry! 🤷

**Pull request merged**
